extends:
  - standard
  - plugin:prettier/recommended
env:
  node: true
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
rules: {}
